name: Validate code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Validate HTML
      run: |
        curl -s -F "uploaded_file=@./path/to/your/index.html;type=text/html" https://validator.w3.org/nu/ > results.html
        grep -q "The document validates" results.html || exit 1
      
    - name: Validate CSS
      run: |
        curl -s -F "file=@./path/to/your/styles.css;type=text/css" https://jigsaw.w3.org/css-validator/validator > results.css
        grep -q "Congratulations! No Error Found." results.css || exit 1
